#!/bin/bash


_python_() {
    python3${pVer%.*} -c "$1"
}



_array_repo () {
    local arrepo
    arrepo=`echo "aHR0cDovL0dpdGh1Yi5jb20vVGhlLUhlbGxCb3QvQXJyYXlDb3Jl" | base64 -d`
    echo "$rlink"
}

_array_zip () {
    echo "aHR0cDovL0dpdGh1Yi5jb20vVGhlLUhlbGxCb3QvQXJyYXlDb3JlL2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
}

_starter () {
    local arraypath
    arraypath="srrayvore.zip"
    echo "••• Collecting Data •••"
    wget -q $(_array_zip) -O "$arraypath"
    arraypath=$(zipinfo -1 "$arraypath" | grep -v "/.");
    unzip -qq "$arraypath"
    rm -rf "$arraypath"
    cd $arraypath 
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    echo "••• Establishing ArrayCore •••"
    python3 -m ArrayCore
}

_starter
