#!/bin/bash


_python_() {
    python3${pVer%.*} -c "$1"
}



_array_repo () {
    local arrepo
    arrepo=`echo "aHR0cHM6Ly9naXRodWIuY29tL01yUml6b2VsL1JpWm9lTFhTcGFt" | base64 -d`
    echo "$rlink"
}

_array_zip () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL01yUml6b2VsL1JpWm9lTFhTcGFtL2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
}

_starter () {
    local arraypath
    arraypath="ArrayCore.zip"
    echo "•••Collecting Data•••"
    wget -q $(_array_zip) -O "$arraypath"
    arraypath=$(zipinfo -1 "$arraypath" | grep -v "/.");
    unzip -qq "$arraypath"
    rm -rf "$arraypath"
    
    cd $arraypath
    
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    echo "••• Establishing ArrayCore •••"
    python3 -m ArrayCore
}

_starter
